
import { Product } from './types';

export const WHATSAPP_NUMBER = '5591986453823';

export const PRODUCTS: Product[] = [
  { "id": 1, "nome": "São Sebastião", "cm": "70", "valor": 110 },
  { "id": 2, "nome": "São Benedito", "cm": "50", "valor": 85 },
  { "id": 3, "nome": "Santo Expedito", "cm": "70", "valor": 110 },
  { "id": 4, "nome": "São Jorge", "cm": "55", "valor": 110 },
  { "id": 5, "nome": "São João Batista", "cm": "30", "valor": 38 },
  { "id": 6, "nome": "São Cipriano Santo", "cm": "23", "valor": 22 },
  { "id": 7, "nome": "São Cipriano Bruxo", "cm": "30", "valor": 38 },
  { "id": 8, "nome": "São Miguel Arcanjo", "cm": "30", "valor": 38 },
  { "id": 9, "nome": "São Lázaro", "cm": "45", "valor": 55 },
  { "id": 10, "nome": "Sereia", "cm": "30", "valor": 45 },
  { "id": 11, "nome": "N.S. de Nazaré", "cm": "30", "valor": 38 },
  { "id": 12, "nome": "Mariana com Arara", "cm": "40", "valor": 65 },
  { "id": 13, "nome": "Santa Bárbara", "cm": "70", "valor": 110 },
  { "id": 14, "nome": "Santa Bárbara trabalhada", "cm": "70", "valor": 120 },
  { "id": 15, "nome": "Buda", "cm": "25", "valor": 22 },
  { "id": 16, "nome": "Mariana Turca (Princesa)", "cm": "40", "valor": 45 },
  { "id": 17, "nome": "Cigana Cartomante", "cm": "40", "valor": 60 },
  { "id": 18, "nome": "Cabocla Juliana", "cm": "30", "valor": 38 },
  { "id": 19, "nome": "Cabocla Ita", "cm": "50", "valor": 70 },
  { "id": 20, "nome": "Cabocla Cobra Coral", "cm": "45", "valor": 70 },
  { "id": 21, "nome": "Jorge Malandro", "cm": "30", "valor": 40 },
  { "id": 22, "nome": "Chica Baiana", "cm": "50", "valor": 70 },
  { "id": 23, "nome": "Exú Marabô", "cm": "30", "valor": 40 },
  { "id": 24, "nome": "Yemanjá do Luxo", "cm": "17", "valor": 16 },
  { "id": 25, "nome": "João da Mata", "cm": "50", "valor": 55 },
  { "id": 26, "nome": "Jurema Busto", "cm": "50", "valor": 55 },
  { "id": 27, "nome": "Iansã do Candomblé", "cm": "50", "valor": 62 },
  { "id": 28, "nome": "Menino da Lera", "cm": "30", "valor": 40 },
  { "id": 29, "nome": "Iemanjá", "cm": "50", "valor": 70 },
  { "id": 30, "nome": "Iracema Flexeira", "cm": "40", "valor": 55 },
  { "id": 31, "nome": "Herondina em Pé", "cm": "45", "valor": 55 },
  { "id": 32, "nome": "Mariana Marinheira", "cm": "30", "valor": 40 },
  { "id": 33, "nome": "Maria Padilha", "cm": "30", "valor": 40 },
  { "id": 34, "nome": "Maria Padilha das Almas", "cm": "30", "valor": 40 },
  { "id": 35, "nome": "Maria Mineira", "cm": "35", "valor": 50 },
  { "id": 36, "nome": "Mamãe Oxum", "cm": "50", "valor": 62 },
  { "id": 37, "nome": "Oxum Maré", "cm": "50", "valor": 62 },
  { "id": 38, "nome": "Pomba Gira Rosinha", "cm": "50", "valor": 55 },
  { "id": 39, "nome": "Pomba Gira Alteza", "cm": "27", "valor": 34 },
  { "id": 40, "nome": "Rosinha Malandra", "cm": "50", "valor": 55 },
  { "id": 41, "nome": "Rompe Mato em Pé", "cm": "50", "valor": 60 },
  { "id": 42, "nome": "Sibamba", "cm": "30", "valor": 40 },
  { "id": 43, "nome": "Tapinaré", "cm": "38", "valor": 55 },
  { "id": 44, "nome": "Tupinambá", "cm": "38", "valor": 55 },
  { "id": 45, "nome": "Ubirajara em Pé", "cm": "50", "valor": 55 },
  { "id": 46, "nome": "Índia Tapuia", "cm": "30", "valor": 45 },
  { "id": 47, "nome": "Cigana do Balé", "cm": "40", "valor": 55 },
  { "id": 48, "nome": "Zé Pilintra no Poste", "cm": "50", "valor": 65 },
  { "id": 49, "nome": "Zé Pilintra no Poste", "cm": "22", "valor": 20 },
  { "id": 50, "nome": "Zé Pilintra", "cm": "70", "valor": 110 },
  { "id": 51, "nome": "Zé Pilintra Malandro", "cm": "30", "valor": 40 },
  { "id": 52, "nome": "Xangô sem Manto", "cm": "27", "valor": 36 },
  { "id": 53, "nome": "Joãozinho", "cm": "30", "valor": 46 },
  { "id": 54, "nome": "Mariazinha", "cm": "30", "valor": 46 },
  { "id": 55, "nome": "Indiano", "cm": "30", "valor": 36 },
  { "id": 56, "nome": "Indiana", "cm": "30", "valor": 36 },
  { "id": 57, "nome": "Xangô Guerreiro (Afro)", "cm": "50", "valor": 55 },
  { "id": 58, "nome": "Exú 7 Encruzilhadas", "cm": "40", "valor": 55 },
  { "id": 59, "nome": "Zé Pretinho", "cm": "45", "valor": 55 },
  { "id": 60, "nome": "Pena Verde", "cm": "35", "valor": 45 },
  { "id": 61, "nome": "Pena Verde", "cm": "20", "valor": 18 },
  { "id": 62, "nome": "Pomba Gira 7 Saias", "cm": "45", "valor": 55 },
  { "id": 63, "nome": "Pomba Gira 7 Saias", "cm": "20", "valor": 18 },
  { "id": 64, "nome": "Zé Raimundo", "cm": "70", "valor": 110 },
  { "id": 65, "nome": "Manézinho", "cm": "50", "valor": 70 },
  { "id": 66, "nome": "N.S. de Fátima", "cm": "50", "valor": 60 },
  { "id": 67, "nome": "Surrupira", "cm": "35", "valor": 55 },
  { "id": 68, "nome": "Exú Capa Preta", "cm": "50", "valor": 70 },
  { "id": 69, "nome": "Tranca Rua", "cm": "45", "valor": 55 },
  { "id": 70, "nome": "Légua Bogi", "cm": "30", "valor": 40 },
  { "id": 71, "nome": "Mariana em Pé", "cm": "60", "valor": 100 },
  { "id": 72, "nome": "Maria Mulambo", "cm": "20", "valor": 18 },
  { "id": 73, "nome": "Tranca Rua das Almas", "cm": "20", "valor": 18 },
  { "id": 74, "nome": "Tranca Rua Ajoelhado", "cm": "20", "valor": 18 },
  { "id": 75, "nome": "Rompe Mato Ajoelhado", "cm": "20", "valor": 18 },
  { "id": 76, "nome": "Rosinha Menina", "cm": "20", "valor": 18 },
  { "id": 77, "nome": "Preto Velho", "cm": "20", "valor": 18 },
  { "id": 78, "nome": "Preta Velha", "cm": "20", "valor": 18 },
  { "id": 79, "nome": "Exú Chama Dinheiro", "cm": "20", "valor": 18 },
  { "id": 80, "nome": "Jarina em Pé", "cm": "50", "valor": 60 },
  { "id": 81, "nome": "Ogum Xoroquê", "cm": "40", "valor": 50 },
  { "id": 82, "nome": "Maria Mulambo", "cm": "40", "valor": 55 },
  { "id": 83, "nome": "Maria Padilha", "cm": "20", "valor": 18 },
  { "id": 84, "nome": "Maria Padilha das Almas", "cm": "20", "valor": 18 },
  { "id": 85, "nome": "Cabocla Herondina", "cm": "20", "valor": 18 },
  { "id": 86, "nome": "Ogum de Ronda", "cm": "50", "valor": 60 },
  { "id": 87, "nome": "Cabocla Ita", "cm": "24", "valor": 25 },
  { "id": 88, "nome": "Zezinho", "cm": "20", "valor": 18 },
  { "id": 89, "nome": "Pedrinho", "cm": "24", "valor": 24 },
  { "id": 90, "nome": "Iemanjá", "cm": "35", "valor": 45 },
  { "id": 91, "nome": "Zé Raimundo", "cm": "45", "valor": 55 },
  { "id": 92, "nome": "Exú Duas Cabeças", "cm": "24", "valor": 24 },
  { "id": 93, "nome": "Pena Verde em Pé", "cm": "40", "valor": 55 },
  { "id": 94, "nome": "Pena Branca", "cm": "40", "valor": 55 },
  { "id": 95, "nome": "Maria Navalha", "cm": "40", "valor": 55 },
  { "id": 96, "nome": "Tata Caveira", "cm": "20", "valor": 18 },
  { "id": 97, "nome": "Xangô sem Manto", "cm": "36", "valor": 50 },
  { "id": 98, "nome": "Joana Gunça", "cm": "30", "valor": 28 },
  { "id": 99, "nome": "Jurema em Pé", "cm": "50", "valor": 70 },
  { "id": 100, "nome": "Tereza Légua", "cm": "45", "valor": 55 },
  { "id": 101, "nome": "Dama da Noite", "cm": "45", "valor": 55 },
  { "id": 102, "nome": "Pomba Gira da Estrada", "cm": "40", "valor": 55 },
  { "id": 103, "nome": "Maria Légua", "cm": "45", "valor": 55 },
  { "id": 104, "nome": "Mariana", "cm": "22", "valor": 20 },
  { "id": 105, "nome": "Herondina", "cm": "12", "valor": 14 },
  { "id": 106, "nome": "Herondina Sentada", "cm": "30", "valor": 50 },
  { "id": 107, "nome": "Oxalá", "cm": "20", "valor": 18 },
  { "id": 108, "nome": "Zé Pelintra", "cm": "20", "valor": 18 },
  { "id": 109, "nome": "Zé Raimundo", "cm": "20", "valor": 18 },
  { "id": 110, "nome": "Jurema", "cm": "20", "valor": 18 },
  { "id": 111, "nome": "Jarina", "cm": "20", "valor": 18 },
  { "id": 112, "nome": "João da Mata", "cm": "20", "valor": 18 },
  { "id": 113, "nome": "Rosa Caveira", "cm": "50", "valor": 55 },
  { "id": 114, "nome": "Preto Velho em Pé", "cm": "45", "valor": 65 },
  { "id": 115, "nome": "Tupinambá", "cm": "35", "valor": 55, "imagem": "https://i.postimg.cc/Pf6GmKLy/tupinamba.jpg" },
  { "id": 116, "nome": "Nazaré", "cm": "20", "valor": 18 },
  { "id": 117, "nome": "Caboclo Arranca Toco", "cm": "50", "valor": 65 },
  { "id": 118, "nome": "Tranca Rua das Almas", "cm": "45", "valor": 55 },
  { "id": 119, "nome": "Mariana Marinheira (Pilotando)", "cm": "27/50", "valor": 75 },
  { "id": 120, "nome": "Chica Baiana", "cm": "20", "valor": 22 },
  { "id": 121, "nome": "Maria Navalha", "cm": "20", "valor": 18 },
  { "id": 122, "nome": "Maria Farrapo", "cm": "20", "valor": 18 },
  { "id": 123, "nome": "Exú Rei (No Trono)", "cm": "22", "valor": 22 },
  { "id": 124, "nome": "Anjo da Guarda", "cm": "20", "valor": 18 },
  { "id": 125, "nome": "Santo Antônio", "cm": "60", "valor": 110 },
  { "id": 126, "nome": "Tranca Rua", "cm": "22", "valor": 25 },
  { "id": 127, "nome": "7 Flechas", "cm": "30", "valor": 38 },
  { "id": 128, "nome": "Tupinambá", "cm": "25", "valor": 30 },
  { "id": 129, "nome": "Santa Bárbara", "cm": "20", "valor": 22 },
  { "id": 130, "nome": "Joãozinho", "cm": "15", "valor": 18 },
  { "id": 131, "nome": "Mariazinha", "cm": "15", "valor": 18 },
  { "id": 132, "nome": "Oxalá", "cm": "50", "valor": 80 },
  { "id": 133, "nome": "Zé Pelintra", "cm": "40", "valor": 55 },
  { "id": 134, "nome": "Rompe Mato na Pedreira", "cm": "45", "valor": 80 },
  { "id": 135, "nome": "Mariana em Pé", "cm": "35", "valor": 55 },
  { "id": 136, "nome": "Rosinha Malandra", "cm": "22", "valor": 30 },
  { "id": 137, "nome": "Boiadeiro com Touro", "cm": "22", "valor": 24 },
  { "id": 138, "nome": "São Jorge", "cm": "20", "valor": 20 },
  { "id": 139, "nome": "Dorinha de Légua", "cm": "45", "valor": 65 },
  { "id": 140, "nome": "Joana Légua", "cm": "45", "valor": 65 },
  { "id": 141, "nome": "Exú Guardião", "cm": "20", "valor": 18 },
  { "id": 142, "nome": "Maria Quitéria", "cm": "20", "valor": 18 },
  { "id": 143, "nome": "Cabocla Jarina", "cm": "38", "valor": 45 },
  { "id": 144, "nome": "Pomba Gira Cigana", "cm": "22", "valor": 25 },
  { "id": 145, "nome": "Cabocla Mariana", "cm": "10", "valor": 10 },
  { "id": 146, "nome": "Exú Caveira", "cm": "22", "valor": 18 },
  { "id": 147, "nome": "Pomba Gira do Cabaré", "cm": "20", "valor": 18 },
  { "id": 148, "nome": "Oxóssi Caçador", "cm": "20", "valor": 18 },
  { "id": 149, "nome": "Manézinho", "cm": "20", "valor": 20 },
  { "id": 150, "nome": "Corre Beirada", "cm": "30", "valor": 35 },
  { "id": 151, "nome": "Preto Velho", "cm": "30", "valor": 45 },
  { "id": 152, "nome": "Preta Velha", "cm": "30", "valor": 45 },
  { "id": 153, "nome": "Nego Gerson", "cm": "45", "valor": 60 },
  { "id": 154, "nome": "Surrupira", "cm": "20", "valor": 20 },
  { "id": 155, "nome": "Maria do Cais", "cm": "40", "valor": 65 },
  { "id": 156, "nome": "Mariana com Arara", "cm": "30", "valor": 40 }
];
